[about]
show=didi

[windows]
main=138,474,86,360,2,0,0
scripts=-9,1627,0,941,0,0,0
wfinger=22,533,22,270,0,1,0
wquery=22,646,22,328,0,1,0
wwwwlist=22,646,22,328,0,1,0
wchannel=22,646,22,328,0,1,0
wdccs=66,646,66,328,0,1,0
wchat=44,448,44,274,0,1,0
wdccg=44,530,44,251,0,1,0
wnotify=26,1608,26,625,0,1,0

[fonts]
fscripts=Verdana,415

[dde]
ServerStatus=on
ServiceName=LAZzARO
CheckName=off

[pfiles]
n0=lazzaro.ini
n1=popups.ini
n2=popups.ini
n3=popups.ini
n4=popups.ini
n5=popups.ini
n5=system\popups.ini
n6=system\popups.ini
n7=system\popups.ini
n8=system\popups.ini
n9=system\popups.ini
n10=intro.mrc
n11=ara2eng.mrc
n12=MRC File.mrc
n13=system\xcl0ne\xpopup.ini
n14=system\xcl0ne\xpopup.ini
n15=system\xcl0ne\xpopup.ini
n16=system\xcl0ne\xpopup.ini


[background]
status=photo\mIRC.bmp,5
#simpson=photo\simpson.bmp,5
Alexius=photo\simpson.bmp,5
#noi=photo\noi.bmp,5
KILLING=photo\nonno.bmp
Mr_MagoO=photo\burns.bmp
sirdoyle=photo\barney.bmp
Grattache=photo\grattachecca.bmp
|cyrax|=photo\krusty.bmp
Marfil=Photo\homer.bmp
#italia=photo\italia.bmp,5
#italia0=photo\italia.bmp,5
#italia2=photo\italia.bmp,5
#italia3=photo\italia.bmp,5
|Antos|=photo\smithers.bmp
ZZ_top=Photo\flanders.bmp
#LazZaro=photo\mIRC.bmp,5
|JAX|=photo\milhouse.bmp
|Scratch|=\photo\homer.bmp
QueryMe=\photo\krusty.bmp
^Sun^=\photo\maggie.bmp
VeLeNo[M]=\photo\milhouse.bmp,5
Frankj=\photo\fichetto.bmp,5
BeLial`=\photo\grattachecca.bmp,5
julie-tte=\photo\maggie.bmp
@mdi=Photo\sfondoo.bmp,1
switchbar=Photo\sfondoo.bmp
toolbuttons=Photo\tool2.bmp
toolbar=Photo\sfondoo.bmp
[warn]
fserve=on
dcc=off

[beeping]


[fileserver]
Warning=on

[dccserver]
n0=0,59,0,0,0,0
n1=1,59,0,0,0,1

[clicks]
status=/lusers
query=/whois $1
channel=/channel
nicklist=/query $1
notify=/whois $1

[ident]
active=yes
userid=Lazzaro.s
system=UNIX
port=1080

[socks]
Enabled=no
Port=1080
Method=4
dccs=yes
hostname=207.50.228.163

[text]
lastreset=[no date]
aptitle=[ -=LazZaro®=- ]
commandchar=/
linesep=-
quit=%quit
ignore=*.exe,*.com,*.bat,*.dll,*.ini
timestamp=[HH:nn]    

[files]
servers=servers.ini
finger=finger.txt
urls=urls.ini
addrbk=ad rbk.ini
browser=c:\progra~1\intern~1\iexplore.exe
emailer=c:\program files\mozilla thunderbird\thunderbird.exe
trayicon=ico.ico

[mirc]
user=LazZaro® Script By  LazZaro........
email=Lazzaro.s@tiscalinet.it
nick=Lazzaro
host=www.intercom.itSERVER:irc.intercom.it:6667
anick=`u1z9g9l5

[dirs]
midis=sounds\
pics=photo\
pics=grafica\

[colours]
n0=0,6,4,13,2,3,3,3,4,3,3,1,5,2,6,1,12,4,3,5,1,15,1,1,0

[options]
n0=1,1,0,0,0,1,200,0,0,1,1,4,1,0,0,0,1,0,0,0,512,0,1,0,0,1,1,0
n1=5,50,0,0,0,0,0,1,19,2,1,1,0,0,2,1,1,1,0,0,1,1,1,0,5,0,1,0,0
n2=1,0,0,0,1,1,1,1,1,60,120,0,0,1,1,0,1,1,0,120,20,10,0,1,1,0,0
n3=500,1,0,1,1,0,0,1,1,1,1,1,0,0,0,0,3,1,0,1,0,0,0,1,1,1,0,0,0
n4=1,0,1,1,0,3,9999,0,0,1,1,0,1024,1,0,1,10,1,0,1,0,1,1,1,1,5000,1
n5=1,1,1,1,1,1,1,1,1,1,34463,1410065407,0,0,0,0,1,1,100,20,4,30,1,22,0,0,1
n6=1,1,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,100,1,1,1,0,1,0,0
[Finger]
n0=user@windgets.co.uk

[wizard]
warning=7

[mirclink]
exe=lazzaro.exe
ini=popups.ini
dde=mIRC

[flashing]


[logging]
status=status.log
#LazZaro=off
[findtext]
n0=Whois
n1=Reg
n2=Reg-=Nick=-
n3=Settaggi
n4=help
n5=lazzaro
n6=team
n7=server
n8=controlla
n9=click

[channelfiles]
n0=channels.txt

[Finger]
n0=212.131.174.156
n1=171.220.14.100
n2=ShocK@195.60.159.69
n3=212.216.170.46
n4=javalite@212.216.171.999
n5=213.255.30.100
n6=213.255.30.10
n7=213.255.30.1
n8=www.105.net
n9=213.255.30.999
n10=213.255.30.231
n11=195.60.145.101
n12=195.60.145.100
n13=195.60.145.1
n14=212.4.3.106
n15=195.60.128.3
n16=195.60.128.1
n17=192.168.4.1
n18=195.60.145.44
n19=proxy.cyberg.it
n20=195.60.159.69

[dccnicks]
n0=Mefisto^
n1=Mic
n2=luca1
n3={Pupa}
n4=NiK`MzK
n5=Mic|{eles
n6=Iaia
n7=|SaSaMaN|
n8=IceX
n9=Rocky
n10=fra1
n11=^^LISA^^
n12=MMarcello
n13=LazZaro®









[extensions]
n0=defaultEXTDIR:download\
n1=*.wav,*.midEXTDIR:sounds\funck.wav
[channels]
n0=#Brindisi
n1=#dreamcast
n2=#emuita
n3=#Fireroom
n4=#firewall
n5=#firewall_room
n6=#game
n7=#infinity
n8=#italia
n9=#iti
n10=#Kchat
n11=#L@arzaro
n12=#LazZaro
n13=#Lecce
n14=#Phreak.it
n15=#pizza
n16=#Roxybar
n17=#Sardegna
n18=#tin
n19=#uhf
[waves]
query=sounds\red hot chilipeppers i°.mp3
disconnect=sounds\trilogy.mid
send=sounds\gianna.mid

[dragdrop]
n0=*.wav:/sound $1 $2-
n1=*.*:/dcc send $1 $2-
s0=*.*:/dcc send $1 $2-

[local]
localip=158.47.251.10
longip=2653944586




[notify]
n0=@BiosNOTE:The Creater Of -=LaZZaro®=-WAVE:sounds\Intro.wav
n1=Dylan
[autoop]
n0=GrazZie per Op
[afiles]
n0=servers.ini
n1=urls.ini
n2=addrbk.ini
n3=mirc.ini
n4=prompt.ini
n5=data\lazzaro.away
n6=aliases.ini
n7=aaliases2.ini
n8=system\multiserver.ini
n9=system\testdcc.ini
n10=system\x24
n11=system\x25
n12=system\x26
n13=system\x27
n14=system\x28
n15=system\x29
n16=system\x30
n17=system\x31
n18=system\x32
n19=system\x33
n20=system\x34
n21=system\x35
n22=system\x36
[rfiles]
n0=ad rbk.ini
n1=remote.ini
n2=mirc.ini
n3=intro.mrc
n4=addon\dcclock.mrc
n5=start.ini
n6=clone.ini
n7=addon\stat.mrc
n8=addon\wars.ini
n9=rawirc.ini
n10=addon\lag.mrc
n11=addon\rr-paint1.mrc
n12=addon\rr-paint2.mrc
n13=addon\portscan2.mrc
n14=addon\socksscan.mrc
n15=addon\socks.mrc
n16=addon\wingate.mrc
n17=addon\logmastr.mrc
n18=addon\telnet.mrc
n19=ircq\ircq.ini
n20=ini\dynscan.mrc
n21=ini\dynatcp.mrc
n22=ini\logview.mrc
n23=toolbar.ini
n24=system\user.txt
n25=system\variabili.var
n26=system\wingate.mrc
n27=system\multiserver.ini
n28=system\testdcc.ini
n29=system\x1
n30=system\x2
n31=system\x3
n32=system\x4
n33=system\x5
n34=system\x6
n35=system\x7
n36=system\x8
n37=system\x9
n38=system\x10
n39=system\x11
n40=system\x12
n41=system\x14
n42=system\x15
n43=system\x16
n44=system\x17
n45=system\x18
n46=system\x20
n47=system\x21
n48=system\x22
n49=system\x23
