;TAKEOVER BOT!!!!! Mirc.ini Del LazZaro Script

[About]                        
show=didi

[Windows]
main=58,563,228,219,2,0,0
wdccs=132,477,132,245,0,1,0
wquery=42,542,42,107,1,1,0
wdccg=198,473,198,226,0,1,0
wchat=63,555,63,120,1,1,0
wchannel=21,555,21,120,0,1,0
wlist=179,621,0,342,0,1,0
wserv=266,266,0,161,0,1,0
wwwwlist=71,610,15,369,0,1,0
wnotify=40,725,37,328,0,0,0
wlinks=66,646,66,331,0,1,0
scripts=4,795,-3,581,0,0,0
status=0,646,0,355,0,1,0

[Logging]

[Fonts]
fstatus=Comic Sans MS,417
fchannel=Fixedsys,415
fquery=Fixedsys,415
fdccsg=FixedSys,-12
flist=FixedSys,-12
ffinger=FixedSys,-12
faliases=Fixedsys,415
fpopups=Fixedsys,415
fremote=Fixedsys,412
fscripts=MS Sans Serif,411
f#LazZaro=Comic Sans MS,417

[DDE]
ServerStatus=on
ServiceName=TakerBot

[Beeping]

[Channels]


[pfiles]
n0=tkbot\popups.ini
n1=tkbot\popups.ini
n2=tkbot\popups.ini
n3=tkbot\popups.ini
n4=tkbot\popups.ini

[wizard]
warning=6

[dccserver]
n0=0,59,0,0,0,0

[warn]
fserve=on
dcc=on

[fileserver]
Warning=on

[DCCNicks]
n0=FrankjWeb
n1=Raffo
n2=Frankj
n3=FigZUseR
n4=[Gi]-[nO]
n5=kekko2
n6=ILoveKate

[clicks]
status=if ($server != $null) { lusers } | else { halt }
query=whois $$1
channel=channel
nicklist=query $$1
notify=whois $$1

[local]
local=m2a2z4
localip=127.0.0.1
longip=2130706433

[ident]
active=no
userid=www
system=UNIX
port=113

[socks]
Enabled=no
HostName=zenith000.hhs.net
Port=1080
Method=4
dccs=no

[text]
lastreset=Tue Jun 09 12:36:16 1998
aptitle=-----------=> ©PОZzЕ §шЈdол®   <=-----------
commandchar=/
linesep=-
finger=pОzZЕ §шЈdол®
quit=pОzZЕ §шЈdол®

[files]
servers=servers.ini
browser=c:\progra~1\intern~1\iexplore.exe
emailer=c:\programmi\netscape\communicator\program\netscape.exe
finger=texts\finger.txt
urls=urls.ini
addrbk=addrbook.ini

[mirc]
user=%nicksol
email=www
nick=Tak3r
anick=S0|d3r
host=127.0.0.1SERVER:127.0.0.1:6667

[dirs]
senddir=d:\nukeandgenocide!!!!!!\icmp\
logdir=logs\
waves=sounds\
midis=sounds\

[colours]
n0=11,6,4,5,6,3,3,3,4,3,3,1,5,2,6,12,3,2,3,5,1,15,1,15,1

[options]
n0=0,1,0,1,0,0,200,1,0,1,1,0,1,1,0,1,0,0,0,1,4096,0,1,4,0,0,1,0
n1=5,50,1,1,118,25,33,0,1,1,1,1,0,0,1,0,1,1,1,0,0,0,0,1,5,0,0,0,0
n2=1,1,0,1,0,1,1,1,0,100,1000,1,1,1,1,0,0,0,1,120,30,10,0,0,1,0,0
n3=500,1,1,0,1,0,1,1,1,1,0,1,0,0,0,1,1,0,0,1,1,1,1,1,1,0,1,0,0
n4=0,0,1,1,0,0,999,0,0,1,1,1,1024,0,1,5,250,0,0,0,0,0,0,1,1,5000
n5=1,1,1,1,1,0,1,1,1,1,6667,0,0,2,0,0,1,0,100,20,4,0,1,22,0,1,1
n6=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,100,1,1,1,0

[dragdrop]
n0=/*.wav:/sound $1 $2
n1=*.*:/dcc send $1 $2
s0=*.*:/dcc send $1 $2-

[extensions]
n0=defaultEXTDIR:download\
n1=*.wav,*.midEXTDIR:sounds\

[afiles]
n0=tkbot\aliases.ini

[rfiles]
n0=tkbot/remote.ini
n1=tkbot/remote.ini
n2=tkbot/blackice.mrc
n3=tkbot/fludmuck.mrc

