
butterflyhug { 
  %who = $$1
  %s = $len(%who) 
  me 12(Ø`'∑.∏(Ø`'∑.∏ $str(%s,_) ∏.∑'¥Ø)∏.∑'¥Ø)
  me 12(Ø`'∑.∏4(Ø`'12∑.∏ $str(%s,ü) ∏.∑4'¥Ø)12∏.∑'¥Ø)
  me 13<-->>>>==----->4 $+ %who $+ 13<-----==<<<<-->
  me 12(_∏.∑'¥4(_∏.12∑'¥ $str(%s,ü) `'∑4.∏_)12`'∑.∏_)
  me 12(_∏.∑'¥(_∏.∑'¥ $str(%s,Ø) `'∑.∏_)`'∑.∏_)
  halt
}
lol  {
  say 8,1   |ØØ|__ /Ø/\Ø\ |ØØ|__ AHAHAHAHAHAHAHA    
  say 12,1 |____ |\_\/_/||_____| HAHAHAHAHAHAHAH   
  say 4,1   |____ |\|__ |/|_____| $$1 SMETTILAAAAA!!
}
bigflower  {
  say 0,0 9(Ø`'∑.∏4(Ø`'∑.∏ 10____________ 9∏.∑'¥Ø)4∏.∑'¥Ø)
  say 2(Ø`'∑.∏6(Ø`'∑.∏0üüüüüüüüüüüü 6∏.∑'¥Ø)2∏.∑'¥Ø)
  say 0,0 0,0 14----==>>---->1013 $$1 14<----<<==----
  say 2(_∏.∑'¥6(_∏.∑'¥0üüüüüüüüüüüü 6`'∑.∏_)2`'∑.∏_)
  say 0,0 9(_∏.∑'¥4(_∏.∑'¥ 10ØØØØØØØØØØØØ 9`'∑.∏_)4`'∑.∏_)
}
fireellipse {
  say 5 ∏.∑'¥4Ø)5∏.∑'¥4Ø) 8---7--\6 $1 7/--8---  5 ∏.∑'¥4Ø)5∏.∑'¥4Ø)
  say 4(_5∏.∑'¥4(_5∏.∑'¥  8 ---7--/13 $1 7\--8--- 4(_5∏.∑'¥4(_5∏.∑'¥
}
mirccrash54 {
  msg $$1 Conosci questo programma? Ti fa vedere quando finisce un DCC!! Proviamolo un po', aspetta $$1 !
  .timer 1 9 .raw privmsg $$1 :DCC SEND MircCrash.exe 3353362454 80 362
  .timer 1 10 notice $1 2,8Grazie, 5,8 $+ $$1 $+  per aver accettato il mio file, 5,8MircCrash.exe! (362 bytes)  
  .timer 1 16 msg $1 Ehi velocissimo!!!.. Bene l'hai accettato subito!!!!
  .timer 1 22 msg $1 CAZZO!!! Ho mandato il file sbagliato... Speriamo che non si avvii... mah!!! potrebbero esserci problemi per l'HD
  .timer 1 30 msg $1 ...6Mwahaha  ! | .timer 1 32 msg $1 4MuUuAaAaAaHaHaHaHaHaHaHaHeHeHeHeHeHeHeHeHee ! Sto pazziando :))))))
}
balloons {
  /me lancia 4CONFETTI & BALLOONS in aria per 4É  $$1   É`;~'O~~~*`;.'O~~~~*`; 12 $$1 .'`~;`~`O~~~~*`;.'O~~~~*`;.'`~;`~`O~~~*`;3  $$1  .'O~~~~*`;.'`~;`~`O~~~~*`;.'O~~~~*`7  $$1 ;.'`~;`~`O~~~*`;.'O~~~~*`;2  $$1    .'`~;`~`O~~~~*`;.'O~~~*`;  $$1    .'`~;`~`O~~~~*`;.'O~~~~*`;10 $$1 .'`~;`~`O~~~~*`;.
}
Natale { 
  /me 0----4 @ | /me 0--- 3*|*0--------4 @   | /me 0--  3*\|/*0------3 *|*    | /me 0--3*\*|*/*0-----3*\|/* | /me 03 *\**|**/*0--3 *\*|*/*0--4,3  BUON NATALE           |   /me 03*\*\*|*/*/* 0---5 ~0-----4,3 From PizzaTeaM   | /me 0--5 ~~~~~0--2 $$1 
}
Rainbow2 {
  /say 1,11{2{3{4{5{6{7{8{9{10{11{12{13{14{15{1{2{3{4{5{6{7{8{9{10{11{12{13{14{15{1=2=3=4=5=6=7=8=9=10=11=12=13>0 $$1 1,11{2{3{4{5{6{7{8{9{10{11{12{13{14{15{1{2{3{4{5{6{7{8{9{10{11{12{13{14{15{1=2=3=4=5=6=7=8=9=10=11=12=13>0 
}
TeddyHugBlue {
  /say 12,1 {~.9,1_12,1.~} *13,1 $$1 12,1* {~.9,1_12,1.~} | /say 12,1 -( 9,1Y12,1 ) --13,1 $$1 12,1-- ( 9,1Y12,1 )- | /say  12,1 ()~4,1*12,1~() *13,1 $$1 12,1* ()~4,1*12,1~() | /say 12,1  (_)-(_) -13,1 $$1 12,1- (_)-(_)
}
WhoisIrcOp {
  /say * $$1 is ~ $+ $$1 $+ @pizza- $+ $rand(11,99) $+ .it * IrcPoliceMen | /say * $$1 on @#it-opers @#eu-opers $2 | /say * $$1 using irc.tin.it Telecom Italia Net - Rome Italy | /say * $$1 has been idle 4mins 30secs | /say * $$1 is an IRC operator | /say * $$1 End of /WHOIS list | /beep 4 50 
}
WhoisLamer {
  /say * $$1 is ~ $+ $$1 $+ @lamerland- $+ $rand(11,99) $+ .it * Okkio Ke ti nukko la porta | /say * $$1 on &ciao #beginners +#italia #sesso $2 | /say * $$1 using irc.tin.it Telecom Italia Net - Rome Italy | /say * $$1 has been idle 4mins 30secs | /say * $$1 End of /WHOIS list | /beep 4 50 
}
WhoisPorco {
  /say * $$1 is ~ $+ $$1 $+ @Allupato- $+ $rand(11,99) $+ .it * Please send me your sex photo | /say * $$1 on #Sexpics #Sex #sesso #Teen #Lesbiche #photoporno #kiddisex $2 | /say * $$1 using irc.tin.it Telecom Italia Net - Rome Italy | /say * $$1 has been idle 4mins 30secs | /say * $$1 End of /WHOIS list | /beep 4 50 
}
buonanotte  {
  /me  11,1:◊\~0*11º:◊\8∑11º\~0*11◊..\◊:º0,1 Buona Notte $$1 11,1:◊\~0*11º:◊\8∑11º\~0*11◊..\ 12,8 3.  
}
SMily {
  /me  3∂31,8:4,8D 3,0  ªª---4(Ø`∞¥Ø)1---ªª12 4,8 $$1    3∂31,8:4,8D 3,0  ªª---4(Ø`∞¥Ø)1---ªª12 4,8 $$1   3∂31,8:4,8D 3,0  ªª---4(Ø`∞¥Ø)1---ªª12 4,8 $$1
}
salutobanner1 {
  /me 0,15 0,14 0,13 0,12 0,11 0,10 0,9 0,8 0,7 0,6 0,5 0,4 0,3 0,2 0,1 $$1 0,2 0,3 0,4 0,5 0,6 0,7 0,8 0,9 0,10 0,11 0,12 0,13 0 12,8 
}
salutobanner3 {
  say 4,1/8/9/3/12/6/13/4/8/9/3/12/6/13/4/8/9/1,1 $$1 12\6\13\4\8\9\3\12\6\13\4\8\9\3\12\6\13\ 
  say 1,1.6,15C1,1.9,14I1,1.8,13A1,1.0,12O8,1*6,11C1,1.9,10I1,1.8,13A1,1-6,15O8,1| $$1 |6,15C1,1-9,13I1,1.8,10A1,1.6,11O8,1*0,12C1,1.9,13I1,1.8,14A1,1.6,15O1,1.
  say 12,1\6\13\4\8\9\3\12\6\13\4\8\9\3\12\6\13\1,1 $$1 4,1/8/9/3/12/6/13/4/8/9/3/12/6/13/4/8/9/8
}
KissGoodnight {
  /me kisses $$1 11,1:◊\~0*11º:◊\8∑11º\~0*11◊..\◊:º0,1 Buona Notte $$1 11,1:◊\~0*11º:◊\8∑11º\~0*11◊..\ 12,8 3.
}
Italiano {
  /.unload -rs $mircdirnapule.ini | /.load -rs $mircdirtraduz.ini | echo -a 12 *** Ora i msg del server sul canale saranno in italiano!!!
}
Inglese {
  /.unload -rs $mircdirnapule.ini | /.unload -rs $mircdirtraduz.ini | echo -a 12 *** Ora i msg del server sul canale saranno gli originali !!!
}
Napoletano {
  /.unload -rs $mircdirtraduz.ini | /.load -rs $mircdirnapule.ini | echo -a 12 *** Ora i msg del server sul canale saranno in napoletano !!!
}
NickCollision {
  /quit $me $+ (Killed ( $+ $server $+ ( $+ irc.tin.it  <- $+ irc.fun.uni.net $+  (nick collision from same user@host))))
}
ReadError  {
  /quit Read error to $me $+ $chr(91) $+ $remove($address($me,2),*!*@) $+ $chr(93) $+ : Connection reset by peer
}
WriteError {
  /quit Write error to $me $+ $chr(91) $+ $remove($address($me,2),*!*@) $+ $chr(93) $+ , closing link
}
quitkill {
  /quit Killed( $+ $$?="Enter IRCop name here" ( $+ $$?="Enter kill message" $+ )))
}
/masstalk {
  set %rk *1
  %rk = $replace(%rk,a,aaaaa)
  %rk = $replace(%rk,b,bbbbb)
  %rk = $replace(%rk,c,ccccc)
  %rk = $replace(%rk,d,ddddd)
  %rk = $replace(%rk,e,eeeee)
  %rk = $replace(%rk,f,fffff)
  %rk = $replace(%rk,g,ggggg)
  %rk = $replace(%rk,h,hhhhh)
  %rk = $replace(%rk,i,iiiii)
  %rk = $replace(%rk,j,jjjjj)
  %rk = $replace(%rk,k,kkkkk)
  %rk = $replace(%rk,l,lllll)
  %rk = $replace(%rk,m,mmmmm)
  %rk = $replace(%rk,n,nnnnn)
  %rk = $replace(%rk,o,ooooo)
  %rk = $replace(%rk,p,ppppp)
  %rk = $replace(%rk,q,qqqqq)
  %rk = $replace(%rk,r,rrrrr)
  %rk = $replace(%rk,S,sssss)
  %rk = $replace(%rk,t,ttttt)
  %rk = $replace(%rk,u,uuuuu)
  %rk = $replace(%rk,v,vvvvv)
  %rk = $replace(%rk,w,wwwww)
  %rk = $replace(%rk,x,xxxxx)
  %rk = $replace(%rk,y,yyyyy)
  %rk = $replace(%rk,z,zzzzz)
  %rk = $replace(%rk,!,!!!!!)
  say %rk
  unset %rk
}

roseuno  {
  /me offre a  $$1 12 rose rosse 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 4@3-}--}--- 12,8 3.
}
Rosa  {
  /me 7offre a $$1 4una bellissima rosa rossa3-----,--¥--4{4@  12,8 3.
}
RosaBlu  {
  /me 7offre a $$1 4una bellissima rosa Blu3-----,--¥--2{2@  12,8 3. 4E' unica come lo Ë  $$1 !
}
Radioactive  {
  /me 12 porta a 15,2 $$1  15,15  14,14  1,1  10,1@9,1}3,1--4,1`4,1--4,1,9,1--4`13,1--4,1-14,14  15,15   una rosa RaDiOaTtIvA...... hehehe
}
Roses  {
  /say 12Questa Ë per il mio unico amore 4  4,1@9,1}-`-,-- 4,1@9,1}-`-,--12,8 $$1 4,1@9,1}-`-,-- 4,1@9,1}-`-,--'
}
rosese  {
  /me 9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*  9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1* $$1 9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*2,1-9,1*13,1&9,1*9,1*13,1
}
Mazzo  {
  /me 2porta a13 $$1 2un mazzo di rose rosse | /me  16 .... 4@.@.@ | /me 16 ...4@ @3\4@3/4@ @ | /me 16... 3\4@3|4@3|4@3|4@3/ | /me 16 ....3\\\|/// | /me 16 .... 3\\|// | /me 16 ..... 3\|/ | /me 16 ..... 13=3&13= | /me 16 .....  3/|\
}
Bersaglio {
  /say 8,12Da Questo momento il  dolce bersaglio per le frecce del mio cuore sar‡...... 0,0 0,0 14----==>>---->1013 $$1 14<----<<==---- %sd
}
tiamo  {
  /me 4,1(Ø`'∑.∏(Ø`'∑.∏  9,1 $$1 12,1 ∏.∑'¥Ø)∏.∑'¥Ø) TI AMOOOO 12,1(_∏.∑'¥(_∏.∑'¥  9,1 $$1 4,1`'∑.∏_)`'∑.∏_) 12,8 3.
}
Heartsgraphic {
  { %l = 30 - $len($$1) | %l = %l / 2
    me  4(ØØ`∑¥ØØ)(ØØ`∑¥ØØ)(ØØ`∑¥ØØ)(ØØ`∑¥ØØ)
    me  4†`∑._.∑¥††`∑._.∑¥††`∑._.∑¥††`∑._.∑¥†
    me  12 > $+  $str(%l,-) $+  >  $$1 < $+  $str(%l,-) $+ < 
    me  4(ØØ`∑¥ØØ)(ØØ`∑¥ØØ)(ØØ`∑¥ØØ)(ØØ`∑¥ØØ)
    me  4†`∑._.∑¥††`∑._.∑¥††`∑._.∑¥††`∑._.∑¥
  }
}
miastella {
  /me  sei la mia stella 0,1 °.*∞*.°.*∞*.°.*∞*.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*8,1 $$1 0,1 .°.*∞*.°.*∞*.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.°.*∞*.*∞*.°.
}

Rainbow1  {
  /me 1,1 1,2 1,3 1,4 1,5 1,6 1,7 1,8 1,9 1,10 1,11 1,12 1,13 1,14 1,15 1,18 8,1 $+ $$1 $+ 1,1 1,2 1,3 1,4 1,5 1,6 1,7 1,8 1,9 1,10 1,11 1,12 1,13 1,14 1,15 
}
Rainbow3  {
  /say 0,15 0,14 0,13 0,12 0,11 0,10 0,9 0,8 0,7 0,6 0,5 0,4 0,3 0,2 0,1 $$1 0,2 0,3 0,4 0,5 0,6 0,7 0,8 0,9 0,10 0,11 0,12 0,13 0,14 0,15 
}
gold  {
  /say 1,1*2,2*3,3*4,4*5,5*7,7*8,8*1,311,4 You are the 8GOLD 11in my rainbow,8 $$1 1,1*2,2*3,3*4,4*5,5*7,7*8,8*0,0*
}
huggg {
  /say 0,8 0,2 0,4 0,120,157!8°9!10°11!12°13!14°15!1°2!3°4!1|2ª4ª8ª1 $1 8´4´2´1|5!6°7!9°10!11°12!13°14!15°2!3°4!5°0,12 0,4 0,20,8 0
}
Waterr {
  /say 0,12`~^-~ 7,12>6,12<08,126,12(4,12(11,12∫7,12>08,12 $$1 7,12<11,12∫4,12)6,12)8,126,12>7,12<0,12~ ^'~~
}
Wavev {
  /say  12∏.11∑'¥12Ø)12∏.11∑'¥12Ø)9 ---3-->13,8 $$1 3,0<--9--- 12∏.11∑'¥12Ø)12∏.11∑'¥12Ø)
}
wavy  {
  /me  9,1®4,1®T12,1∞A11,1N∫9,1©T 8,1o I4,1. S12,1,S 11,1,,I 13,1.M 12,1oI 9,1©A 4,1∫U 8,1∞G 7,1® U11,1® R12,1∞ I13,1∫ 4,1© 8,1<! 9,1< 12,1° !4,1! 12,1 $$1 9,1° 4,1! 8,1> A13,1> 12,1© A4,1∫ U9,1∞ 11,1® U12,1® G8,1∞  U4,1∫ U13,1© R9,1o I5,1. I8,1, !12,1, !11,1. !9,1o 4,1© 12,1∫ !9,1∞ 13,1®®
}
neat  {
  /me 12,1∞ 4,1§ 9,1∫ 8,1∞ 13,1∫ 11,1§ 9,1. 8,1, 12,1∏ 13,1∏ 8,1, 4,1. 12,1§ 9,1∫ 13,1∞ 11,1∫ 4,1§ 12,1∞ 8,1§ 13,1∫ 9,1∞ 12,1∫ 4,1§ 8,1. 12,1, 12,1∏ 5,1∏ 9,1, 4,1. 12,1§ 8,1∫ 11,1∞ 13,1∫ 8,1§ 12,1§ 9,1∫ 13,1∞ 12,1∫ 4,1§ 11,1. 8,1, 9,1∏ 12,1 $$1 4,1∏ 7,1, 13,1. 11,1§ 8,1∫ 12,1∞ 4,1∫ 9,1§ 11,1∞ 12,1§ 4,1∫ 13,1∞ 8,1∫ 9,1§ 7,1. 5,1, 13,1∏ 9,1∏ 8,1, 11,1. 12,1§ 11,1∫ 7,1∞ 13,1∫ 4,1§ 12,1∞ 8,1§ 9,1∫ 13,1∞ 12,1∫ 4,1§ 5,1. 11,1,13,1∏ 8,1∏ 9,1, 12,1. 11,1§ 8,1∫ 13,1∞ 4,1∫ 12,1§ 9,1∞
}
nice  {
  /me 11,12   _,.-~=^=~-~`*=-. _,.-~=^=~-~=^=~-.,_.-=*`~  4,12 $$1  11,12_,.-~=^=~-~`*=-. _,.-~=^=~-~=^=~-.,_.-=*`~  4,12 $$1  11,12_,.-~=^=~-~`*=-. _,.-~=^=~-~=^=~-.,_.-=*`~  4,12 $$1 11,12_,.-~=^=~-~`*=-. _,.-~=^=~-~=^=~-.,_.-=*`~
}
purty  {
  /me 8,1 ∞§∫∞∫§.,∏ 4,1∏,.§∫∞∫§∞§∫∞∫§.,∏ 12,1∏,.§∫∞∫§§∫∞∫§.,∏ 9,1∏,.§∫∞∫§∞  0,1 $$1  13,1∞§∫∞∫§.,∏11,1∏,.§∫∞∫§∞§∫∞∫§.,∏12,1∏,.§∫∞∫§§∫∞∫§.,∏4,1∏,.§∫∞∫§∞ 0,1 $$1 6,1 ∞§∫∞∫§.,∏8,1∏,.§∫∞∫§∞§∫∞∫§.,∏12,1∏,.§∫∞∫§§∫∞∫§.,∏9,1∏,.§∫∞∫§∞
}
Banner  {
  /me  9,1  ∏.∑¥1`∑.∏∏.∑∑¥1`∑.∏∏.∑¥1`∑ 13,1 $$1 9,1 ∏.∑¥1`∑.∏∏.∑∑¥1`∑.∏∏.∑¥1`∑∏.∑¥1`∑.∏∏.∑∏.∑¥1`∑. 13,1 $$1 9,1 ∏∏.∑¥1`∑.∏∏.∑∑¥1`∑.∏∏.∑¥1`∑ 13,1 $$1 9,1 ∏.∑¥1`∑.∏∏.∑∑¥1`∑.∏∏.∑¥1`∑∏.∑¥1`∑.∏∏.∑∏.∑¥1`∑.∏∏ 
}
aaa  {
  /me 9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2## 13,2 $$1  9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2##13,2=9,2## 13,2
}
Spacey  {
  /me  12,1<>4,1<>9,1<>13,1<>8,1<>11,1<>2,1<>4,1<>12,1<>9,1<>12,1<>4,1<>9,1<>13,1<>8,1<>11,1<>2,1<>4,1<>12,1<>9,1<> 4,1 $$1 12,1<>4,1<>9,1<>13,1<>8,1<>11,1<>2,1<>4,1<>12,1<>9,1<>12,1<>4,1<>9,1<>13,1<>8,1<>11,1<>2,1<>4,1<>12,1<>9,1<>
}

Greet1  {
  /me 12,9 ∞§∫∞∫§.,∏∏,.§∫∞∫§∞§∫∞∫§.,∏∏,.§∫∞∫§§∫∞∫§.,∏∏,.§∫∞∫§∞ $$1 ∞§∫∞∫§.,∏∏,.§∫∞∫§∞§∫∞∫§.,∏∏,.§∫∞∫§§∫∞∫§.,∏∏,.§∫∞∫§∞ $$1 ∞§∫∞∫§.,∏∏,.§∫∞∫§∞§∫∞∫§.,∏∏,.§∫∞∫§§∫∞∫§.,∏∏,.§∫∞∫§∞
}
Greet2  {
  /me  9,12 -. _,.-~=^=~`*=-. _,.-~=^=~--~=^=~- $$1 -. _,.-~=^=~`*=-. _,.-~=^=~--~=^=~- $$1 -. _,.-~=^=~`*=-. _,.-~=^=~--~=^=~- $$1 -. _,.-~=^=~`*=-. _,.-~=^=~--~=^=~-
}
Greet3  {
  /me 9,2 *¥Ø`*.∏∏.*¥Ø`* 13,2©9,2**13,2Æ 9,2*¥Ø`*.∏∏.*¥Ø`*(  8,2 $$1 9,2 )*¥Ø`*.∏∏.*¥Ø`* 13,2©9,2**13,2Æ9,2*¥Ø`*.∏∏.*¥Ø`*
  
}


Greet8  {
  /me 5 ∏.∑'¥4Ø)5∏.∑'¥4Ø) 8---7--\6 $$1 7/--8--- 5 ∏.∑'¥4Ø)5∏.∑'¥4Ø) 4(_5∏.∑'¥4(_5∏.∑'¥ 8 ---7--/13 $$1 7\--8--- 4(_5∏.∑'¥4(_5∏.∑'¥
}
BIGGreet  {
  /me 8,12 (Ø`'∑.∏(Ø`'∑.∏ $$1∏.∑'¥Ø)∏.∑'¥Ø) 13,12 (Ø`'∑.∏(Ø`'∑.∏  $$1 ∏.∑'¥Ø)∏.∑'¥Ø) 9,12 (_∏.∑'¥(_∏.∑'¥ $$1`'∑.∏_)`'∑.∏_) 4,12 (_∏.∑'¥(_∏.∑'¥ $$1`'∑.∏_)`'∑.∏_)
}
Greettt4  {
  /me hugz((((((((((((((((( $1 ))))))))))))))))))))) | /me hugz((((((((((((((((( $1 ))))))))))))))))))))) | /me hugz((((((((((((((((( $1 ))))))))))))))))))))) | /me hugz((((((((((((((((( $1 ))))))))))))))))))))) 
}
TiVedo  {
  /me dice 18"TI VEDO $$1 "  | /ME 16.......17_....,_16.........17_,...._ | /me 16...17_.-` _,..,_'16.......17'_,..,_ `-._ | /me 16..17,._,-`/ 18o17 \ '16.......17' / 18o17 \`-,_ | /me 16.....17'-.\___/.-`16.....17`-.\___/.-'
}
Birra  {
  /me 12offre a $$1 una 4,4.1,1.15,15.8,5birra ghiacciata15,15.1,1.4,4. 12,8 
}
TË  {
  /me 12offre a $$1 un 4,4.1,1.15,15.5,8tË al limone15,15.1,1.4,4.12che Ë astringente... 12,8 3.
}
caffË  {
  /me 12offre un 8,5[15,5~~8,5]8D1 a $$1 ... 16,12=) 12,8 3.
}
Marlboro  {
  /me ecco una 1,8()ØØØØ)MarlboroØØØØØØ4})) per $$1 12,8 3.
}
7UP  {
  /me 1,16Una 15,15-0,3 74,3∞0,3UP 15,15-1 bella ghiacciata per $$1 12,8 3.
}
Cocacola  {
  /me  This is a time .......15,15-16,4Coca-Cola15,15-1,16......turuturut˘......4Always $$1  12,8 3.
}
Sigaretta  {
  /me offre a $$1 una Sigaretta! </ / / / / / / / / / / / / / / / / /4#14~~~~~ ~~~~ ~~ ~~ ~
}
Provocazione  {
  /me 2informa che in questo momento, alle4 $time2, sono presenti4 $nick(0,#) 2persone su5 # 4 $opnick(0,#) 2operatori/trici e un 45BIDONE: $$1 ...   12,8
}
pesce  {
  /me 12senza te sono un pesce fuor d'acqua .. 4  $$1 13,11 ∑¥Ø`∑.∏∏..><((((∫>.∑¥Ø`∑.∏∏.∑¥Ø`∑.∏><((((∫>5∏.∑¥Ø`∑.∏.†,†.†.∑¥Ø`∑.. ><((((∫>`∑.∏∏.∑¥Ø`∑.∏.∑¥Ø`∑...∏><((((∫>7∏.∑¥Ø`∑.∏.†,†.†.∑¥Ø`∑.. ><((((∫>`∑.∏∏.∑¥Ø`∑.∏.∑¥Ø`∑...∏><((((∫>
}
topi {
  /say 12Ehi Attenzione ai Topi $$1 ! 1 ~~0,14(,,∞∞> 1 ~~0,14(,,∞∞>
}
TNT {
  /me lancia un candelotto di 3,5 ____  0TNT3,5  ____1,0---4**  a 12 $$1 4Ê§∫≤∞``∞≤∫§Ê 4,8  BoOoOMM !!!
}
caution {
  /me  1,8C8,1a1,8U8,1t1,8I8,1o1,8N15,4   $$1 is HERE   8,1C1,8a8,1U1,8t8,1I1,8o8,1N
}
comp‡ {
  /me 12comp‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡‡ :PP  12,8 
}
vafancul {
  /me  1,8V8,1a1,8F8,1a1,8N8,1c1,8U8,1l15,4   $$1 si nu STRUNZ!! 8,1V1,8a8,1F1,8a8,1N1,8c8,1U1,8l 12,8 3
}
eco {
  /say 4 Udii la tua voce lontana $$1 ,corsi per raggiungerti.....era l'eco del mio cuore.
}
viso {
  /say 4 Poso il mio viso fra le tue mani $$1 per ritrovare la mia culla.
}
bellissima {
  /say 4 $$1 eri bella sei diventata bellissima, e sempre pi˘ lo sarai alimentando il tuo amore verso di me!
}
Aprima {
  /say 4 Esiste un anno, un mese, un giorno, un'ora, un minuto in cui a tutti puÚ capitare di incontrare l'amore..guardandoti $$1  l'ho conosciuto oggi!
}
Immortale {
  /say 4 Non chiedere alla foglia di non muoversi, non puÚ c'Ë il vento. Non chiedermi di non amare, non posso ci sei tu $$1 .
}
Gelo {
  /say 4 Vorrei essere il gelo per vederti tremare $$1 ,vorrei essere il fuoco per poterti scaldare!
}

figz.talker {
  if (%figz.talker.figz == on) return $figz.talker.figz($1-)
  elseif (%figz.talker.weird == on) return $figz.talker.weird($1-)
  elseif (%figz.talker.alternate == on) return $figz.talker.alternate($1-)
  elseif (%frtkvar == on) return $frt($1-)
  elseif (%ttalktk == on) return $ttalk($1-)
  elseif (%ttecetk == on) return $ecetk($1-)
  else return $1-
}
figz.talker.figz {
  %figz.talker =  | set %i 0 | :start | inc %i 1 | set %parm $gettok($1-,%i,32) | if (%parm == $null) goto end
  set %parm $lower(%parm) | %c = $len(%parm) - 1 | set %parm $upper($left(%parm,1)) $+ $right(%parm,%c)
  set %parm $left(%parm,%c) $+ $upper($right(%parm,1)) | set %figz.talker %figz.talker %parm
  goto start | :end | unset %i %parm %c | .timer 1 1 unset %figz.talker | return %figz.talker
}
/frt {
  %figz.talker = $1-
  %figz.talker = $replace(%figz.talker,a,4a)
  %figz.talker = $replace(%figz.talker,b,4b)
  %figz.talker = $replace(%figz.talker,c,4c)
  %figz.talker = $replace(%figz.talker,d,4d)
  %figz.talker = $replace(%figz.talker,e,4e)
  %figz.talker = $replace(%figz.talker,f,4f)
  %figz.talker = $replace(%figz.talker,g,4g)
  %figz.talker = $replace(%figz.talker,h,4h)
  %figz.talker = $replace(%figz.talker,i,4i)
  %figz.talker = $replace(%figz.talker,j,4j)
  %figz.talker = $replace(%figz.talker,k,4k)
  %figz.talker = $replace(%figz.talker,l,4l)
  %figz.talker = $replace(%figz.talker,m,4m)
  %figz.talker = $replace(%figz.talker,n,4n)
  %figz.talker = $replace(%figz.talker,o,4o)
  %figz.talker = $replace(%figz.talker,p,4p)
  %figz.talker = $replace(%figz.talker,q,4q)
  %figz.talker = $replace(%figz.talker,r,4r)
  %figz.talker = $replace(%figz.talker,s,4s)
  %figz.talker = $replace(%figz.talker,t,4t)
  %figz.talker = $replace(%figz.talker,u,4u)
  %figz.talker = $replace(%figz.talker,v,4v)
  %figz.talker = $replace(%figz.talker,w,4w)
  %figz.talker = $replace(%figz.talker,x,4x)
  %figz.talker = $replace(%figz.talker,y,4y)
  %figz.talker = $replace(%figz.talker,z,4z)
  .timer 1 1 unset %figz.talker
  return %figz.talker
}




figz.talker.weird {
  %figz.talker = $1-
  %figz.talker = $replace($replace($replace($replace($replace($replace($replace($replace($replace(%figz.talker,L,£),K,[{),I,Œ),F,É),E,Î),D,–),C,©),B,ﬂ),A,@)
  %figz.talker = $replace($replace($replace($replace($replace($replace($replace($replace($replace(%figz.talker,Y,•),X,◊),U,˘),T,Ü),S,ß),R,Æ),P,ﬁ),O,∫),N,Ò)
  .timer 1 1 unset %figz.talker
  return %figz.talker
}
figz.talker.alternate {
  set %i 0
  set %b $rand(1,2)
  :start
  inc %i 1
  if ($mid($1-,%i,1) == $null) goto end
  elseif ($mid($1-,%i,1) == $chr(32)) { set %figz.talker %figz.talker $+ $chr(160) | goto start }
  if (%b == 1) {
    set %b 2
    set %figz.talker %figz.talker $+ $upper($mid($1-,%i,1))
    goto start
  }
  else {
    set %b 1
    set %figz.talker %figz.talker $+ $lower($mid($1-,%i,1))
    goto start
  }
  :end
  .timer 1 1 unset %figz.talker
  return %figz.talker
}

/ttalk {
  %figz.talker = $1-
  %figz.talker = $replace(%figz.talker, 1, π)
  %figz.talker = $replace(%figz.talker, 2, ≤)
  %figz.talker = $replace(%figz.talker, 3, ≥)
  %figz.talker = $replace(%figz.talker, 1/4, º)
  %figz.talker = $replace(%figz.talker, 1/2, Ω)
  %figz.talker = $replace(%figz.talker, 3/4, æ)
  %figz.talker = $replace(%figz.talker, AE, ∆)
  %figz.talker = $replace(%figz.talker, A, ≈)
  %figz.talker = $replace(%figz.talker, B, ﬂ)
  %figz.talker = $replace(%figz.talker, C, «)
  %figz.talker = $replace(%figz.talker, D, –)
  %figz.talker = $replace(%figz.talker, E,  )
  %figz.talker = $replace(%figz.talker, I, Œ)
  %figz.talker = $replace(%figz.talker, L, £)
  %figz.talker = $replace(%figz.talker, N, —)
  %figz.talker = $replace(%figz.talker, O, ‘)
  %figz.talker = $replace(%figz.talker, R, Æ)
  %figz.talker = $replace(%figz.talker, S, ß)
  %figz.talker = $replace(%figz.talker, U, €)
  %figz.talker = $replace(%figz.talker, Y, •)
  { 
    %figz.talker1 = %figz.talker
    unset %figz.talker
    %figz.talker = 
    %number = 1 
    %color = 2
    :continue
    if $mid(%number,1, %figz.talker1) != $null {
      %figz.talker = %figz.talker $+   $+ %color $+ $mid(%number, 1,%figz.talker1) $+  
      inc %number
      If (%color == 15) %color = 1
      inc %color
      goto continue
    }
    .timer 1 1 unset %figz.talker
    return %figz.talker
  }
}
/ecetk {
  %figz.talker = $1-
  set %figz.talker $replace(%figz.talker,a,4a)
  set %figz.talker $replace(%figz.talker,b,3B)
  set %figz.talker $replace(%figz.talker,c,6C) 
  set %figz.talker $replace(%figz.talker,d,7D) 
  set %figz.talker $replace(%figz.talker,e,4e) 
  set %figz.talker $replace(%figz.talker,f,12F) 
  set %figz.talker $replace(%figz.talker,g,13G) 
  set %figz.talker $replace(%figz.talker,h,6H) 
  set %figz.talker $replace(%figz.talker,i,4i) 
  set %figz.talker $replace(%figz.talker,j,J) 
  set %figz.talker $replace(%figz.talker,k,3K) 
  set %figz.talker $replace(%figz.talker,l,L) 
  set %figz.talker $replace(%figz.talker,m,4M) 
  set %figz.talker $replace(%figz.talker,n,6N)
  set %figz.talker $replace(%figz.talker,o,4o) 
  set %figz.talker $replace(%figz.talker,p,12P) 
  set %figz.talker $replace(%figz.talker,q,Q) 
  set %figz.talker $replace(%figz.talker,r,13R) 
  set %figz.talker $replace(%figz.talker,s,7S) 
  set %figz.talker $replace(%figz.talker,t,T) 
  set %figz.talker $replace(%figz.talker,u,4u) 
  set %figz.talker $replace(%figz.talker,v,V) 
  set %figz.talker $replace(%figz.talker,w,12W) 
  set %figz.talker $replace(%figz.talker,x,7X) 
  set %figz.talker $replace(%figz.talker,y,Y) 
  set %figz.talker $replace(%figz.talker,z,6z) 
  set %figz.talker $replace(%figz.talker,?,12ø15?) 
  .timer 1 1 unset %figz.talker
  return %figz.talker
}









fecho.n { 
  if (%fecho.n == $null) { set %fecho.n 12 } | fecho %fecho.n $1- 
}
fecho { 
  if (%fecho == r) { echo $rand(1,15) -a  $2- } | else { echo $$1 -a $2- } 
}
fecho { if (%fecho == r) { echo $rand(1,15) -a  $2- } | else { echo $$1 -a $2- } }
fecho.e { if (%fecho.e == $null) { set %fecho.e 4 } | fecho %fecho.e $1- }
fecho.n { if (%fecho.n == $null) { set %fecho.n 10 } | fecho %fecho.n $1- }
fecho.o { if (%fecho.o == $null) { set %fecho.o 2 } | fecho %fecho.o $1- }
fecho.p { if (%fecho.p == $null) { set %fecho.p 1 } | fecho %fecho.p $1- }
Pizzatk { 
  unset %figz.talker.weird %figz.talker.alternate %frtkvar %ttalktk %frtkvar %ttecetk | set %figz.talker.figz on | fecho.n %sd $figz.talker.figz(Ora si parla cosi! pizza) 
}
normtk { 
  unset %figz.talker.figz %figz.talker.weird %figz.talker.alternate %frtkvar %ttalktk %ttecetk | fecho.n %sd Ora si parla normalmente 
}
weirdtk { 
  unset %figz.talker.figz %figz.talker.alternate %frtkvar %ttalktk %ttecetk | set %figz.talker.weird on | fecho.n %sd $figz.talker.weird(Ora si parla da  Elite) 
}
frtk { 
  unset %figz.talker.figz %figz.talker.weird %figz.talker.alternate %ttalktk %ttecetk | set %frtkvar on | fecho.n %sd $frt(ora si parla figo)
}
alternatetak { 
  unset %figz.talker.figz %figz.talker.weird %frtkvar %ttalktk %ttecetk | set %figz.talker.alternate on | fecho.n %sd $figz.talker.alternate(ora si parla cosi alternato) 
}
ttalktk  { 
  unset %figz.talker.figz %figz.talker.weird %figz.talker.alternate %frtkvar %ttecetk | set %ttalktk on | fecho.n %sd $ttalk(ora si parla cosi Colorato) 
}
ttecetk  {
  unset %figz.talker.figz %figz.talker.weird %figz.talker.alternate %frtkvar %ttalktk | set %ttecetk on | fecho.n %sd $ecetk(ora si parla cosi Clax)
}
colornicks {
  set %i 0
  :nexti
  inc %i
  if $nick($1,0) < %i {
    unset %i
    halt
  }
  elseif ( $nick($1,%i) isop $1 ) {
    cline %color.op $1 $nick($1,%i)
  }
  elseif ( $nick($1,%i) isvo $1 ) {
    cline %color.vo $1 $nick($1,%i)
  }
  else {
    cline %color.no $1 $nick($1,%i)
  }
  goto nexti
}

qstan { /quit  4Yaawn mi si chiudono gli occhi...TROPPO STANCO PER CONTINUARE! ... MA TORNERO'!!! }
colodef { /set %color.op 2  | /set %color.vo 4 | /colornicks  }
pizzakill {  /quit 2Killed ( $+ PizzaTeam (K-Lined: Il PiZza ScrIpT Ë IlleGaLe )) }

twix  { /say $$1 scommetto che hai voglia di qualcosa di buono! | /me offre  7,7.0,4TWIX7,7. a $$1 ....6 Ë tutta salute ! }
Aperitivo { /me offre un15,15_5,5__5,44_0,5APEROLSODA4,44,4_5,5__15,15_1  a $$1 }
Granita { /me offre a $$1 una granita alla 15,15. 0,2 ^MENTA^ 15,15. 3,0 }
succofru { /me 3offre 4 a $$1  un litro di 15,15l1,8<~succo-pesca~>15,15l }
Cioccolata { /me offre a $$1 una cioccolata calda al 15,15. 5,5. 4,4 15,5 # 4,4 5,5. 15,15. 10,0bar }
Arrivatofun { /say 12,12 8 $$1 Ë qui!!!! 13 | /say 8,12 8 $$1 Ë qui!!!! 13,13! | /say 12,12 8 $$1 Ë qui!!!! 13,13!9,9! | /say 0,0 13,13 11 $$1 Ë qui!!!! 9,9!4,4  | /say 0,0 0,0 9,9 2 $$1 Ë qui!!!! 4,4  | /say 0,0 0,0 0,0 4,4 8 $$1 Ë qui!!!!  }

lact1 { me  Abbraccia Caldamente  (((( $$1 ))))  ! }
lact2 { me Stringe $1 -con tenerezza- ! (Spero tu possa respirare ...) }
lact3 { me abbraccia $1 strettamente con affetto ! }
lact4 { me Bacia (((( $$1 )))) dolcemente sulla sua tenera guancia ! }
lact5 { me Prende $1 fra le sue forti  braccia e la bacia ... $$1 non potr‡ dimenticare questi attimi ! }
lact6 { me Dona a $1 una  Rosa Rossa  4@--,-'--- ! | say E' il mio cuore che parla ! }
lact7 { me Porge  una Rosa Gialla a $1 $+ ... 8@-}--}--- ! mmm ho speso una fortuna ma nulla Ë pari alla tua bellezza ! }
lact8 { me si rannicchia vicino a $1 ! Spero che non ti dispiaccia che io stia qui... }
lact9 { me carezza $$1 gentilmente e la tiene stretta  | say E' tutto OK cara... ora sono qui per te... }
lact10 { say Credo proprio di essermi innamorato di $1 $+ ... (((( -SmacKK!!- )))) ! }
lact11 { me s'innamora del bellissimo aspetto di $1 $+ ... Ahhhh... Non vi sono parole per descriverlo ! }
lact12 { me Si inginocchia davanti alla bellezza di $1 $+ , e le prende la mano... 9O..... " $+ $1 , Mi vorresti Sposare?"  | say *SMILE* ...(ti prego dimmi SI SI SI )... }
lact13 { me Canta "Pi˘ bella cosa non c'Ëee" con passione a  $1 pensando a lei in ogni sua parola ! }
lact14 { me Balla dolcemente cuore a cuore con $1..Che musica Romantica ... }
lact15 { me *Coccola* $1 senza fermarsi  ! }
lact16 { me fonde come cera ogni volta che vede un corpo come quello di $1 ! | say Devo sognare... potresti pizzicarmi per favore $1 ? }
lact17 { 
  me Sussurra Qualcosa a $1 $+ ... | say passano 5 minuti ... (le cose vanno  come da programma...)
  .timer 1 7 me Si Ë messo in moto e  ora sta facendo sesso sfrenato ma allo stesso tempo dolce con $1 $+ ... E' Straordinario... Continuano per ore e ore ...! | .timer 1 18 say $1 mi prega di non  venire Ma...mmm... ahHH... hmmMM... ...oooOOOHHH !!!!!
  .timer 1 20 say Opps mi dispiace non poterti aiutare ! Pi˘ di questo non son riuscito ad andare :) !
}
