@ECHO OFF
@DEL RISULTATI.TXT
@CLS
ECHO. 
ECHO IIIIIIII  CCCCCCCCCCCCCCC. MMMMM        MMMMM  PPPPPPPPPPPP
ECHO          CCCCCCCC CCCCCCCC MMMMMM      MMMMMM PPPPPPPPPPPPPPP 
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM    MMMMMMM PPPPPP   PPPPPP
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMMM  MMMMMMMM PPPPPPPPPPPPPPP
ECHO IIIIIIII CCCCCCCC          MMMMMMMMMMMMMMMMMM PPPPPPPP     PP  
ECHO IIIIIIII CCCCCCCC          MMMMMMMMMMMMMMMMMM PPPPPPP PPPPP    
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM MM MMMMMMM PPPPPPP 
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM    MMMMMMM PPPPPPP 
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM    MMMMMMM PPPPPPP
ECHO IIIIIIII  CCCCCCCCCCCCCCC  MMMMMMM    MMMMMMM PPPPPPP
ECHO.      
ECHO                 Ricercatore ICMP V1.0 by Lobotomia
ECHO.
ECHO Ricerca per le connessioni ICMP....
ECHO. >> RESULTS.TXT
ECHO IIIIIIII  CCCCCCCCCCCCCCC. MMMMM        MMMMM  PPPPPPPPPPPP  >> RISULTATI.TXT
ECHO          CCCCCCCC CCCCCCCC MMMMMM      MMMMMM PPPPPPPPPPPPPPP >> RISULTATI.TXT
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM    MMMMMMM PPPPPP   PPPPPP >> RISULTATI.TXT
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMMM  MMMMMMMM PPPPPPPPPPPPPPP >> RISULTATI.TXT
ECHO IIIIIIII CCCCCCCC          MMMMMMMMMMMMMMMMMM PPPPPPPP     PP >> RISULTATI.TXT
ECHO IIIIIIII CCCCCCCC          MMMMMMMMMMMMMMMMMM PPPPPPP PPPPP  >> RISULTATI.TXT
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM MM MMMMMMM PPPPPPP  >> RISULTATI.TXT
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM    MMMMMMM PPPPPPP  >> RISULTATI.TXTT
ECHO IIIIIIII CCCCCCCC CCCCCCCC MMMMMMM    MMMMMMM PPPPPPP >> RISULTATI.TXT
ECHO IIIIIIII  CCCCCCCCCCCCCCC  MMMMMMM    MMMMMMM PPPPPPP >> RISULTATI.TXT
ECHO. >> RISULTATI.TXT
ECHO                 Ricercatore ICMP V1.0 by Lobotomia >> RISULTATI.TXT
@ARP -a >> RISULTATI.TXT
ECHO. >> RISULTATI.TXT
ECHO -=+=-=+=-=+=-=+=-=+=-=+=-=+=- >> RISULTATI.TXT
@NETSTAT -s -p icmp >> RISULTATI.TXT
ECHO. >> RISULTATI.TXT
ECHO -=+=-=+=-=+=-=+=-=+=-=+=-=+=- >> RISULTATI.TXT
ECHO   Ricercatore ICMP V1.0 by Lobotomia >> RISULTATI.TXT
ECHO         v1.0.A >> RESULTS.TXT
ECHO -=+=-=+=-=+=-=+=-=+=-=+=-=+=- >> RISULTATI.TXT
ECHO Ricerca fatta.. Caricamento dei risultati.
C:\WINDOWS\NOTEPAD.EXE RISULTATI.TXT
@EXIT